### ISSUE TITLE
Where can I get the right DLL?

### ISSUE THREAD

**Issue by hugo-sna** [MasonLeeBack/libscepad_windows_sdk#1]

**Comment by MasonLeeBack** [comment]
Apologies for not seeing this earlier! Most consumer games which have Sony gamepad support should have the right DLL. This pulls the export data from whichever version you're using so it shouldn't really matter which version you have.

**Comment by hugo-sna** [comment]
Do you some exemples of games that the latest version of the DLL, I want to use it with the dualsense but can't any games with the right version
